# Generated by Django 5.2 on 2025-04-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGruop',
            new_name='ChatGroup',
        ),
    ]
